[package]
name = "unibs-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
repository = "https://github.com/Mik3rizzo/typst-unibs-thesis"
authors = ["Michele Rizzo"]
license = "GPL-3.0"
description = "A modern thesis template for the University of Brescia."
keywords = ["thesis", "unibs", "university", "Brescia", "Università degli Studi di Brescia"]
categories = ["thesis"]
compiler = "0.11.0"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"